version: "3"

services:
  python-app:
    build: ./python-app
    ports:
      - "8080:$PORT"  # Sử dụng cổng từ Railway
    environment:
      - FLASK_APP=app.py
      - PORT=8080  # Đảm bảo Flask sử dụng cổng đúng
    command: flask run --host=0.0.0.0 --port=$PORT
    depends_on:
      - php-app

  php-app:
    build: ./php-app
    ports:
      - "8080:$PORT"  # Cũng sử dụng cổng từ Railway
    command: apache2-foreground
